### ISSUE TITLE
Cek mutasi tidak bisa

### ISSUE THREAD

**Issue by vivakreasi** [karnadixyz/mandiri-scraper#2]
Kenapa ya kang cek mutasi false terus padahal cek saldo bisa?Trims sebelumnya

**Comment by karnadixyz** [comment]
Saya coba berjalan lancar baik cek saldo maupun mutasi.

**Comment by vivakreasi** [comment]
kayaknya ada kelemahan kang, kalo di mandiri mutasinya terlalu banyak dia
error, contoh nih saya ada teman yg mutasinya banyak , di mandiri
ebankingnya dia butuh waktu load nya 40-50 detikan, di coding akang
langsung output false, tapi kalau mutasi dikit normal. Ada saran kang?
